apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model
          image: your-image-repository/model-image:latest  # Replace with your model image
          ports:
            - containerPort: 5000
            - containerPort: 8000  # Port for /metrics endpoint
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: default
spec:
  ports:
    - port: 5000
      targetPort: 5000  # API endpoint port
    - port: 8000
      targetPort: 8000  # Metrics endpoint port
  selector:
    app: model-service
