apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-api
  namespace: mlrun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-api
  template:
    metadata:
      labels:
        app: blue-api
    spec:
      containers:
        - name: blue-api
          image: 192.168.117.185:8087/mlops/tf/final_5:latest # Match the output of your BuildConfig
          ports:
            - containerPort: 8080  # Flask app default port (adjust if different)
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi

---

kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: blue-api 
  namespace: mlrun
spec:
  output:
    to:
      kind: DockerImage
      name: '192.168.117.185:8087/mlops/tf/final_5:latest'
  source:
    type: Binary
    binary: {}
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "1"
      memory: 1Gi
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
